/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afsistemas;


/**
 *
 * @author Anthony
 */
import java.awt.event.*;
import javax.swing.JFrame;
import java.awt.*;
import afsistemas.Cliente;


public class AFsistemas extends javax.swing.JFrame {

    public int contadorCadastro=1;
  public int contadorVendas=2;
  public int contadorRelatorio=3;  
  public int contadorCaixa=4;
  public int contadorFCaixa=5;
    public int contadorPulo=0;
    
    public AFsistemas() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Cliente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Vendas = new javax.swing.JButton();
        Conf = new javax.swing.JButton();
        Relatorio = new javax.swing.JButton();
        Agenda = new javax.swing.JButton();
        Pedidos = new javax.swing.JButton();
        ordemServico = new javax.swing.JButton();
        FechaAbas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1151, 653));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        Home.setAutoscrolls(true);
        Home.setFocusTraversalPolicyProvider(true);
        Home.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Home.setInheritsPopupMenu(true);
        Home.setMaximumSize(new java.awt.Dimension(1280, 800));
        Home.setPreferredSize(new java.awt.Dimension(1151, 653));
        Home.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                HomeComponentRemoved(evt);
            }
        });
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel2.setRequestFocusEnabled(false);

        Cliente.setBackground(new java.awt.Color(37, 61, 168));
        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administrator_100px_1.png"))); // NOI18N
        Cliente.setMnemonic('C');
        Cliente.setToolTipText("Cliente: Cadastro, Pesquisa.");
        Cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        Cliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/administrator_100px.png"))); // NOI18N
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(37, 61, 168));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_move_by_trolley_100px.png"))); // NOI18N
        jButton2.setMnemonic('P');
        jButton2.setToolTipText("Produtos.");
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_move_by_trolley_100px_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Vendas.setBackground(new java.awt.Color(37, 61, 168));
        Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cash_register_filled_100px.png"))); // NOI18N
        Vendas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        Vendas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cash_register_filled_100px_1.png"))); // NOI18N
        Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendasActionPerformed(evt);
            }
        });

        Conf.setBackground(new java.awt.Color(37, 61, 168));
        Conf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_settings_100px.png"))); // NOI18N
        Conf.setToolTipText("Configurações");
        Conf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        Conf.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_settings_100px_1.png"))); // NOI18N
        Conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfActionPerformed(evt);
            }
        });

        Relatorio.setBackground(new java.awt.Color(37, 61, 168));
        Relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_download_pie_chart_report_100px_1.png"))); // NOI18N
        Relatorio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatorio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        Relatorio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_download_pie_chart_report_100px.png"))); // NOI18N
        Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioActionPerformed(evt);
            }
        });

        Agenda.setBackground(new java.awt.Color(37, 61, 168));
        Agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_calendar_22_100px.png"))); // NOI18N
        Agenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agenda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        Agenda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_calendar_22_100px_1.png"))); // NOI18N
        Agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendaActionPerformed(evt);
            }
        });

        Pedidos.setBackground(new java.awt.Color(37, 61, 168));
        Pedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_deliver_food_100px_1.png"))); // NOI18N
        Pedidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedidos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        Pedidos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_deliver_food_100px.png"))); // NOI18N
        Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosActionPerformed(evt);
            }
        });

        ordemServico.setBackground(new java.awt.Color(37, 61, 168));
        ordemServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_maintenance_filled_100px.png"))); // NOI18N
        ordemServico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "O.S", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        ordemServico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_maintenance_filled_100px_1.png"))); // NOI18N
        ordemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordemServicoActionPerformed(evt);
            }
        });

        FechaAbas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_shutdown_64px.png"))); // NOI18N
        FechaAbas.setText("Fechar Abas");
        FechaAbas.setContentAreaFilled(false);
        FechaAbas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FechaAbas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_shutdown_64px_1.png"))); // NOI18N
        FechaAbas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        FechaAbas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaAbasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(FechaAbas)
                .addGap(406, 406, 406)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Agenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Conf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Vendas, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(Pedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(ordemServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Vendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(FechaAbas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Conf, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(Agenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ordemServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        Home.addTab("Principal", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(477, 477, 477)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE))
        );

        Home.getAccessibleContext().setAccessibleName("Principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_HomeComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeComponentRemoved

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        /*Cliente form = new Cliente();
        Home.add("Cliente",form);
        form.setVisible(true);*/
        Cliente cont = new Cliente();
        //Home.removeAll();
        Home.add("Cliente",cont);
        Home.revalidate();
        Home.setVisible(true);
        contadorPulo++;
        contadorVendas = 1;

    }//GEN-LAST:event_ClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*Cliente form = new Cliente();
        Home.add("Cliente",form);
        form.setVisible(true);*/
        Produtos cont = new Produtos();
        //Home.removeAll();
        Home.add("Produtos",cont);
        Home.revalidate();
        Home.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendasActionPerformed
        /*Cliente form = new Cliente();
        Home.add("Cliente",form);
        form.setVisible(true);*/
        AFVendas cont = new AFVendas();
        //Home.removeAll();
        /*Home.add("Vendas",cont);
        Home.revalidate();*/
        cont.setVisible(true);
        
        contadorVendas = 2;
        
    }//GEN-LAST:event_VendasActionPerformed

    private void FechaAbasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaAbasActionPerformed
        
        
        if(contadorVendas == 2){
        }
        
    }//GEN-LAST:event_FechaAbasActionPerformed

    private void RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioActionPerformed
        /*Cliente form = new Cliente();
        Home.add("Cliente",form);
        form.setVisible(true);*/
        Relatorio cont = new Relatorio();
        //Home.removeAll();
        Home.add("Relatorio",cont);
        Home.revalidate();
        Home.setVisible(true);
    }//GEN-LAST:event_RelatorioActionPerformed

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        /* if(contadorVendas == 2){
        Home.remove(WIDTH);
        }*/
    }//GEN-LAST:event_HomeMouseExited

    private void AgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendaActionPerformed
         /*Cliente form = new Cliente();
        Home.add("Cliente",form);
        form.setVisible(true);*/
        Agenda cont = new Agenda();
        //Home.removeAll();
        Home.add("Agenda",cont);
        Home.revalidate();
        Home.setVisible(true);
    }//GEN-LAST:event_AgendaActionPerformed

    private void ConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfActionPerformed
         /*Cliente form = new Cliente();
        Home.add("Cliente",form);
        form.setVisible(true);*/
        Configuracao cont = new Configuracao();
        //Home.removeAll();
        Home.add("Configuracao",cont);
        Home.revalidate();
        Home.setVisible(true);
    }//GEN-LAST:event_ConfActionPerformed

    private void PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosActionPerformed
        /*Cliente form = new Cliente();
        Home.add("Cliente",form);
        form.setVisible(true);*/
        Pedido ped = new Pedido();
        //Home.removeAll();
        Home.add("Pedido",ped);
        Home.revalidate();
        Home.setVisible(true);
    }//GEN-LAST:event_PedidosActionPerformed

    private void ordemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordemServicoActionPerformed
       
               /*Cliente form = new Cliente();
        Home.add("Cliente",form);
        form.setVisible(true);*/
        OS ords = new OS();
        //Home.removeAll();
        Home.add("O.S",ords);
        Home.revalidate();
        Home.setVisible(true);
    }//GEN-LAST:event_ordemServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFsistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFsistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFsistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFsistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFsistemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agenda;
    public javax.swing.JButton Cliente;
    private javax.swing.JButton Conf;
    private javax.swing.JButton FechaAbas;
    public javax.swing.JTabbedPane Home;
    private javax.swing.JButton Pedidos;
    private javax.swing.JButton Relatorio;
    private javax.swing.JButton Vendas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public transient javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ordemServico;
    // End of variables declaration//GEN-END:variables
}
