/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afsistemas;

import javax.swing.JFrame;

/**
 *
 * @author Evan
 */
public class AFVendas extends javax.swing.JFrame {

    /**
     * Creates new form AFVendas
     */
    public AFVendas() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AFSistemas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Painel_Esquerdo = new javax.swing.JPanel();
        Quantidade = new javax.swing.JLabel();
        Painel_Imagem = new javax.swing.JPanel();
        Image = new javax.swing.JLabel();
        Quantidade_texto = new javax.swing.JTextField();
        Produto = new javax.swing.JLabel();
        Produto_texto = new javax.swing.JTextField();
        TotalBruto1 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        Inserir = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        AFSistemas.setBackground(new java.awt.Color(45, 111, 143));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vendas");

        javax.swing.GroupLayout AFSistemasLayout = new javax.swing.GroupLayout(AFSistemas);
        AFSistemas.setLayout(AFSistemasLayout);
        AFSistemasLayout.setHorizontalGroup(
            AFSistemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AFSistemasLayout.createSequentialGroup()
                .addGap(862, 862, 862)
                .addComponent(jLabel1)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        AFSistemasLayout.setVerticalGroup(
            AFSistemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AFSistemasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Painel_Esquerdo.setBackground(new java.awt.Color(71, 136, 174));
        Painel_Esquerdo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Painel_Esquerdo.setToolTipText("");

        Quantidade.setBackground(new java.awt.Color(255, 255, 255));
        Quantidade.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Quantidade.setForeground(new java.awt.Color(255, 255, 255));
        Quantidade.setText("Quantidade");

        Painel_Imagem.setBackground(new java.awt.Color(255, 255, 255));

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        Image.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout Painel_ImagemLayout = new javax.swing.GroupLayout(Painel_Imagem);
        Painel_Imagem.setLayout(Painel_ImagemLayout);
        Painel_ImagemLayout.setHorizontalGroup(
            Painel_ImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ImagemLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Image)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_ImagemLayout.setVerticalGroup(
            Painel_ImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ImagemLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Quantidade_texto.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Quantidade_texto.setToolTipText("Nome Completo do Cliente.");
        Quantidade_texto.setAutoscrolls(false);

        Produto.setBackground(new java.awt.Color(255, 255, 255));
        Produto.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Produto.setForeground(new java.awt.Color(255, 255, 255));
        Produto.setText("Produto");

        Produto_texto.setBackground(new java.awt.Color(255, 255, 195));
        Produto_texto.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Produto_texto.setToolTipText("Nome Completo do Cliente.");
        Produto_texto.setAutoscrolls(false);

        TotalBruto1.setBackground(new java.awt.Color(255, 255, 255));
        TotalBruto1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        TotalBruto1.setForeground(new java.awt.Color(255, 255, 255));
        TotalBruto1.setText("Total Bruto");

        jFormattedTextField2.setBackground(new java.awt.Color(45, 111, 143));
        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0,00")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextField2.setEnabled(false);
        jFormattedTextField2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N

        Inserir.setBackground(new java.awt.Color(255, 255, 255));
        Inserir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Inserir.setForeground(new java.awt.Color(255, 255, 255));
        Inserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save_as_filled_50px_2.png"))); // NOI18N
        Inserir.setBorder(null);

        Limpar.setBackground(new java.awt.Color(255, 255, 255));
        Limpar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Limpar.setForeground(new java.awt.Color(255, 255, 255));
        Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_broom_50px.png"))); // NOI18N
        Limpar.setBorder(null);

        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_plus_math_52px_1.png"))); // NOI18N
        jButton1.setText("Adicionar");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_plus_math_52px.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout Painel_EsquerdoLayout = new javax.swing.GroupLayout(Painel_Esquerdo);
        Painel_Esquerdo.setLayout(Painel_EsquerdoLayout);
        Painel_EsquerdoLayout.setHorizontalGroup(
            Painel_EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                .addGroup(Painel_EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Quantidade))
                    .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Produto)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                .addGroup(Painel_EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Painel_Imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                        .addGroup(Painel_EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(Painel_EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                                        .addComponent(Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Painel_EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Produto_texto, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addComponent(Quantidade_texto, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextField2))))
                            .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(TotalBruto1)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_EsquerdoLayout.setVerticalGroup(
            Painel_EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EsquerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Quantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Quantidade_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Produto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Produto_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(TotalBruto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(Painel_EsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTable2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Produto", "Quantidade", "R$ Unitário", "R$ Total"
            }
        ));
        jTable2.setFillsViewportHeight(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(80);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(80);
            jTable2.getColumnModel().getColumn(1).setMinWidth(900);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(900);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(900);
            jTable2.getColumnModel().getColumn(2).setMinWidth(300);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(300);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(300);
            jTable2.getColumnModel().getColumn(3).setMinWidth(180);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(180);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(180);
            jTable2.getColumnModel().getColumn(4).setMinWidth(200);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(200);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        jPanel1.setBackground(new java.awt.Color(45, 111, 143));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AFSistemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Painel_Esquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AFSistemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Painel_Esquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AFSistemas;
    private javax.swing.JLabel Image;
    private javax.swing.JButton Inserir;
    private javax.swing.JButton Limpar;
    private javax.swing.JPanel Painel_Esquerdo;
    private javax.swing.JPanel Painel_Imagem;
    private javax.swing.JLabel Produto;
    private javax.swing.JTextField Produto_texto;
    private javax.swing.JLabel Quantidade;
    private javax.swing.JTextField Quantidade_texto;
    private javax.swing.JLabel TotalBruto1;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
