/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afsistemas;

/**
 *
 * @author Anthony
 */
public class OS extends javax.swing.JPanel {

    /**
     * Creates new form OS
     */
    public OS() {
        initComponents();
        BtDelete.setEnabled(false);
    }
    boolean menuDisplay = false;
    boolean menuDisplay1 = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        PainelPesquisaAdd = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        PainelAdicionar = new javax.swing.JPanel();
        PainellProduto = new javax.swing.JPanel();
        NSerie = new javax.swing.JLabel();
        CampoNSerie = new javax.swing.JTextField();
        Cor = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        Descricao = new javax.swing.JLabel();
        CampoDescricao = new javax.swing.JTextField();
        ComboBoxCor = new javax.swing.JComboBox<>();
        ComboBoxMarca = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PainelCliente = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CPFCNPJ = new javax.swing.JLabel();
        CampoCPFCNPJ = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PainelAvaliacaoTecnica = new javax.swing.JPanel();
        Diagnostico = new javax.swing.JLabel();
        CampoDiagnostico = new javax.swing.JTextField();
        Entrega = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        BtVoltar = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtLimpar = new javax.swing.JButton();
        PainelAtendimento = new javax.swing.JPanel();
        Tecnico = new javax.swing.JLabel();
        Local = new javax.swing.JLabel();
        Contato = new javax.swing.JLabel();
        Solicitante = new javax.swing.JLabel();
        CampoTecnico = new javax.swing.JTextField();
        CampoLocal = new javax.swing.JTextField();
        CampoContato = new javax.swing.JTextField();
        CampoSolicitante = new javax.swing.JTextField();
        Obs = new javax.swing.JLabel();
        CampoObs = new javax.swing.JTextField();
        BtDelete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtAdicionar = new javax.swing.JButton();
        BtPesquisar = new javax.swing.JButton();
        Pesquisa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CampoPesquisa = new javax.swing.JTextField();
        PainelAdd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PainelOrdemDeServico = new javax.swing.JPanel();
        OrdemDeServico = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        PainelPesquisaAdd.setBackground(new java.awt.Color(245, 245, 245));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        PainelAdicionar.setBackground(new java.awt.Color(255, 255, 255));

        PainellProduto.setBackground(new java.awt.Color(255, 255, 255));
        PainellProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        PainellProduto.setToolTipText("Produto");

        NSerie.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        NSerie.setText("Nº Serie:");

        CampoNSerie.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CampoNSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNSerieActionPerformed(evt);
            }
        });

        Cor.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Cor.setText("Cor:");

        Marca.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Marca.setText("Marca:");

        Descricao.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Descricao.setText("Descrição:");

        CampoDescricao.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CampoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDescricaoActionPerformed(evt);
            }
        });

        ComboBoxCor.setEditable(true);
        ComboBoxCor.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        ComboBoxMarca.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxMarca.setEditable(true);
        ComboBoxMarca.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("O.s:");

        javax.swing.GroupLayout PainellProdutoLayout = new javax.swing.GroupLayout(PainellProduto);
        PainellProduto.setLayout(PainellProdutoLayout);
        PainellProdutoLayout.setHorizontalGroup(
            PainellProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainellProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CampoNSerie)
                .addGap(18, 18, 18)
                .addComponent(Cor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Marca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PainellProdutoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainellProdutoLayout.setVerticalGroup(
            PainellProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainellProdutoLayout.createSequentialGroup()
                .addGroup(PainellProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainellProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NSerie)
                    .addComponent(CampoNSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cor)
                    .addComponent(Marca)
                    .addComponent(ComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descricao)
                    .addComponent(CampoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        PainelCliente.setBackground(new java.awt.Color(255, 255, 255));
        PainelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        Nome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Nome.setText("Nome:");

        CampoNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        CPFCNPJ.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CPFCNPJ.setText("CPF / CNPJ:");

        CampoCPFCNPJ.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jTextField1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Codigo:");

        javax.swing.GroupLayout PainelClienteLayout = new javax.swing.GroupLayout(PainelCliente);
        PainelCliente.setLayout(PainelClienteLayout);
        PainelClienteLayout.setHorizontalGroup(
            PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CPFCNPJ)
                .addGap(18, 18, 18)
                .addComponent(CampoCPFCNPJ)
                .addContainerGap())
        );
        PainelClienteLayout.setVerticalGroup(
            PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelClienteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFCNPJ)
                    .addComponent(CampoCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PainelAvaliacaoTecnica.setBackground(new java.awt.Color(255, 255, 255));
        PainelAvaliacaoTecnica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Avaliação Tecnica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        Diagnostico.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Diagnostico.setText("Diagnostico:");

        CampoDiagnostico.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        Entrega.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Entrega.setText("Entrega:");

        javax.swing.GroupLayout PainelAvaliacaoTecnicaLayout = new javax.swing.GroupLayout(PainelAvaliacaoTecnica);
        PainelAvaliacaoTecnica.setLayout(PainelAvaliacaoTecnicaLayout);
        PainelAvaliacaoTecnicaLayout.setHorizontalGroup(
            PainelAvaliacaoTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAvaliacaoTecnicaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PainelAvaliacaoTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoDiagnostico)
                    .addGroup(PainelAvaliacaoTecnicaLayout.createSequentialGroup()
                        .addGroup(PainelAvaliacaoTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Diagnostico)
                            .addGroup(PainelAvaliacaoTecnicaLayout.createSequentialGroup()
                                .addGroup(PainelAvaliacaoTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Entrega)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelAvaliacaoTecnicaLayout.setVerticalGroup(
            PainelAvaliacaoTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAvaliacaoTecnicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Diagnostico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAvaliacaoTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelAvaliacaoTecnicaLayout.createSequentialGroup()
                        .addComponent(Entrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        BtVoltar.setBackground(new java.awt.Color(255, 255, 255));
        BtVoltar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left_squared_filled_50px_1.png"))); // NOI18N
        BtVoltar.setMnemonic('V');
        BtVoltar.setText("Voltar");
        BtVoltar.setToolTipText("Voltar");
        BtVoltar.setBorder(null);
        BtVoltar.setContentAreaFilled(false);
        BtVoltar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left_squared_filled_50px_3.png"))); // NOI18N
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });

        BtSalvar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save_as_filled_50px_2.png"))); // NOI18N
        BtSalvar.setMnemonic('S');
        BtSalvar.setText("Salvar");
        BtSalvar.setToolTipText("Salvar");
        BtSalvar.setBorder(null);
        BtSalvar.setContentAreaFilled(false);
        BtSalvar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save_as_filled_50px.png"))); // NOI18N
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtLimpar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_broom_50px.png"))); // NOI18N
        BtLimpar.setMnemonic('L');
        BtLimpar.setText("Limpar");
        BtLimpar.setToolTipText("LImpar os campos.");
        BtLimpar.setBorder(null);
        BtLimpar.setContentAreaFilled(false);
        BtLimpar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_broom_50px_1.png"))); // NOI18N
        BtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparActionPerformed(evt);
            }
        });

        PainelAtendimento.setBackground(new java.awt.Color(255, 255, 255));
        PainelAtendimento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atendimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        Tecnico.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Tecnico.setText("Tecnico:");

        Local.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Local.setText("Local:");

        Contato.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Contato.setText("Contato:");

        Solicitante.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Solicitante.setText("Solicitante:");

        CampoTecnico.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        CampoContato.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        CampoSolicitante.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        Obs.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Obs.setText("Observação:");

        CampoObs.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout PainelAtendimentoLayout = new javax.swing.GroupLayout(PainelAtendimento);
        PainelAtendimento.setLayout(PainelAtendimentoLayout);
        PainelAtendimentoLayout.setHorizontalGroup(
            PainelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAtendimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAtendimentoLayout.createSequentialGroup()
                        .addComponent(Tecnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Local, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Contato)
                        .addGap(18, 18, 18)
                        .addComponent(CampoContato, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Solicitante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelAtendimentoLayout.createSequentialGroup()
                        .addComponent(Obs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoObs)))
                .addGap(15, 15, 15))
        );
        PainelAtendimentoLayout.setVerticalGroup(
            PainelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAtendimentoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PainelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tecnico)
                    .addComponent(CampoTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Local)
                    .addComponent(CampoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contato)
                    .addComponent(Solicitante)
                    .addComponent(CampoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Obs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtDelete.setBackground(new java.awt.Color(255, 255, 255));
        BtDelete.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BtDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_filled_50px_2.png"))); // NOI18N
        BtDelete.setMnemonic('D');
        BtDelete.setText("Deletar");
        BtDelete.setToolTipText("Deletar Cadastro");
        BtDelete.setBorder(null);
        BtDelete.setContentAreaFilled(false);
        BtDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtDelete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_filled_50px_3.png"))); // NOI18N
        BtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDeleteActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_update_file_48px.png"))); // NOI18N
        jButton2.setMnemonic('A');
        jButton2.setText("Atualizar");
        jButton2.setToolTipText("Atualiza O.S");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_update_file_48px_2.png"))); // NOI18N

        javax.swing.GroupLayout PainelAdicionarLayout = new javax.swing.GroupLayout(PainelAdicionar);
        PainelAdicionar.setLayout(PainelAdicionarLayout);
        PainelAdicionarLayout.setHorizontalGroup(
            PainelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainellProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelAdicionarLayout.createSequentialGroup()
                        .addComponent(BtVoltar)
                        .addGap(67, 67, 67)
                        .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PainelAvaliacaoTecnica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PainelAdicionarLayout.setVerticalGroup(
            PainelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtVoltar)
                    .addComponent(BtSalvar)
                    .addComponent(BtLimpar)
                    .addComponent(BtDelete)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainellProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelAvaliacaoTecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(PainelAdicionar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(PainelAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BtAdicionar.setBackground(new java.awt.Color(245, 245, 245));
        BtAdicionar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        BtAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_50px.png"))); // NOI18N
        BtAdicionar.setText("Adicionar");
        BtAdicionar.setToolTipText("Física ou Juridica");
        BtAdicionar.setBorder(null);
        BtAdicionar.setBorderPainted(false);
        BtAdicionar.setContentAreaFilled(false);
        BtAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtAdicionar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_50px_1.png"))); // NOI18N
        BtAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtAdicionarMouseEntered(evt);
            }
        });
        BtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAdicionarActionPerformed(evt);
            }
        });

        BtPesquisar.setBackground(new java.awt.Color(245, 245, 245));
        BtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_50px.png"))); // NOI18N
        BtPesquisar.setToolTipText("Pesquisar");
        BtPesquisar.setBorder(null);
        BtPesquisar.setBorderPainted(false);
        BtPesquisar.setContentAreaFilled(false);
        BtPesquisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_50px_1.png"))); // NOI18N
        BtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarActionPerformed(evt);
            }
        });

        Pesquisa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Pesquisa.setText("Pesquisa");

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_print_filled_100px.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_print_filled_100px_1.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout PainelPesquisaAddLayout = new javax.swing.GroupLayout(PainelPesquisaAdd);
        PainelPesquisaAdd.setLayout(PainelPesquisaAddLayout);
        PainelPesquisaAddLayout.setHorizontalGroup(
            PainelPesquisaAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaAddLayout.createSequentialGroup()
                .addGroup(PainelPesquisaAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPesquisaAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelPesquisaAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtAdicionar)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPesquisaAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Pesquisa)
                                .addComponent(BtPesquisar))))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );
        PainelPesquisaAddLayout.setVerticalGroup(
            PainelPesquisaAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaAddLayout.createSequentialGroup()
                .addComponent(BtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1))
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        CampoPesquisa.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CampoPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), null));
        CampoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPesquisaActionPerformed(evt);
            }
        });

        PainelAdd.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout PainelAddLayout = new javax.swing.GroupLayout(PainelAdd);
        PainelAdd.setLayout(PainelAddLayout);
        PainelAddLayout.setHorizontalGroup(
            PainelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAddLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelAddLayout.setVerticalGroup(
            PainelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPrincipalLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(PainelPesquisaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(CampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 1438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(CampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(PainelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PainelPesquisaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PainelOrdemDeServico.setBackground(new java.awt.Color(51, 51, 255));

        OrdemDeServico.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        OrdemDeServico.setForeground(new java.awt.Color(240, 240, 240));
        OrdemDeServico.setText("Ordem de Serviço");

        javax.swing.GroupLayout PainelOrdemDeServicoLayout = new javax.swing.GroupLayout(PainelOrdemDeServico);
        PainelOrdemDeServico.setLayout(PainelOrdemDeServicoLayout);
        PainelOrdemDeServicoLayout.setHorizontalGroup(
            PainelOrdemDeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOrdemDeServicoLayout.createSequentialGroup()
                .addGap(543, 543, 543)
                .addComponent(OrdemDeServico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelOrdemDeServicoLayout.setVerticalGroup(
            PainelOrdemDeServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOrdemDeServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrdemDeServico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(PainelOrdemDeServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelOrdemDeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtAdicionarMouseEntered
        /*if(menuDisplay == true){
            menuDisplay = false;
            jLayeredPane2.setSize(0, getHeight());
            jPanel5.setSize(0, getHeight());
            jPanel0.setSize(70,getHeight());
        }*/
    }//GEN-LAST:event_BtAdicionarMouseEntered

    private void BtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAdicionarActionPerformed
        if(menuDisplay == false ){
            menuDisplay = true;

            PainelAdicionar.setSize(1980, getHeight());
            jLayeredPane1.setSize(1980,getHeight());
            PainelPesquisaAdd.setSize(1980,getHeight());
            menuDisplay1 = false;
        }
    }//GEN-LAST:event_BtAdicionarActionPerformed

    private void CampoNSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNSerieActionPerformed

    private void CampoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDescricaoActionPerformed

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
        if(menuDisplay == true){
            menuDisplay = false;

            PainelAdicionar.setSize(0, getHeight());
            jLayeredPane1.setSize(0,getHeight());
            PainelPesquisaAdd.setSize(70,getHeight());
            menuDisplay1 = false;
        }
    }//GEN-LAST:event_BtVoltarActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        // salvar();
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
        // limpacampos();
    }//GEN-LAST:event_BtLimparActionPerformed

    private void BtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtDeleteActionPerformed

    private void BtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarActionPerformed
        //mostrar();
        if(menuDisplay = true){
            menuDisplay = false;

            PainelAdicionar.setSize(0, getHeight());
            jLayeredPane1.setSize(0,getHeight());
            PainelPesquisaAdd.setSize(70,getHeight());
        }
        if(menuDisplay1 = true){
            menuDisplay1 = false;

            PainelAdicionar.setSize(0, getHeight());
            jLayeredPane1.setSize(0,getHeight());
            PainelPesquisaAdd.setSize(70,getHeight());
        }
    }//GEN-LAST:event_BtPesquisarActionPerformed

    private void CampoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPesquisaActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAdicionar;
    private javax.swing.JButton BtDelete;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JButton BtPesquisar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JButton BtVoltar;
    private javax.swing.JLabel CPFCNPJ;
    private javax.swing.JFormattedTextField CampoCPFCNPJ;
    private javax.swing.JTextField CampoContato;
    private javax.swing.JTextField CampoDescricao;
    private javax.swing.JTextField CampoDiagnostico;
    private javax.swing.JTextField CampoLocal;
    private javax.swing.JTextField CampoNSerie;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoObs;
    private javax.swing.JTextField CampoPesquisa;
    private javax.swing.JTextField CampoSolicitante;
    private javax.swing.JTextField CampoTecnico;
    private javax.swing.JComboBox<String> ComboBoxCor;
    private javax.swing.JComboBox<String> ComboBoxMarca;
    private javax.swing.JLabel Contato;
    private javax.swing.JLabel Cor;
    private javax.swing.JLabel Descricao;
    private javax.swing.JLabel Diagnostico;
    private javax.swing.JLabel Entrega;
    private javax.swing.JLabel Local;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel NSerie;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Obs;
    private javax.swing.JLabel OrdemDeServico;
    private javax.swing.JPanel PainelAdd;
    private javax.swing.JPanel PainelAdicionar;
    private javax.swing.JPanel PainelAtendimento;
    private javax.swing.JPanel PainelAvaliacaoTecnica;
    private javax.swing.JPanel PainelCliente;
    private javax.swing.JPanel PainelOrdemDeServico;
    private javax.swing.JPanel PainelPesquisaAdd;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel PainellProduto;
    private javax.swing.JLabel Pesquisa;
    private javax.swing.JLabel Solicitante;
    private javax.swing.JLabel Tecnico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
